# This file was generated by GoReleaser. DO NOT EDIT.
class Gorillang < Formula
  desc "gorillang"
  homepage "https://github.com/momotaro98/gorillang"
  version "1.0.13"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/momotaro98/gorillang/releases/download/v1.0.13/gorillang_1.0.13_Darwin_x86_64.tar.gz"
    sha256 "6f24ca6c3dff4632731f0c24ab1d032b0c3db76931f7c155afa4894e63c737e6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/momotaro98/gorillang/releases/download/v1.0.13/gorillang_1.0.13_linux_x86_64.tar.gz"
      sha256 "1eadb45e7105322453583e35070788d1eb26f63b55034058ea77e833aeea63b4"
    end
  end

  def install
    bin.install "gorillang"
  end

  test do
    system "#{bin}/gorillang --version"
  end
end
