# This file was generated by GoReleaser. DO NOT EDIT.
class Gorillang < Formula
  desc "gorillang"
  homepage "https://github.com/momotaro98/gorillang"
  version "1.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/momotaro98/gorillang/releases/download/v1.0.8/gorillang_1.0.8_Darwin_x86_64.tar.gz"
    sha256 "fbaa85b983e8e7309efdb4fb4efd90b2c9e11469ed8e013b05d925bcbdf8b96d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/momotaro98/gorillang/releases/download/v1.0.8/gorillang_1.0.8_linux_x86_64.tar.gz"
      sha256 "cf0cfc4eb8fa12d808c56c8d1ee3cba23e4b9f9a5d18aa58e95523b7f4d68d9b"
    end
  end

  def install
    bin.install "gorillang"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
