# This file was generated by GoReleaser. DO NOT EDIT.
class Gorillang < Formula
  desc "gorillang"
  homepage "https://github.com/momotaro98/gorillang"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/momotaro98/gorillang/releases/download/v1.0.6/gorillang_1.0.6_Darwin_x86_64.tar.gz"
    sha256 "254f4f8a2e61bd831dbcb5c2692c9440554d296ad662a05dc3f495918a0b91d5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/momotaro98/gorillang/releases/download/v1.0.6/gorillang_1.0.6_linux_x86_64.tar.gz"
      sha256 "aac53ae2a768d87067aa4edcf56ae19f279955d5cadf8d5fc1801959e2a36bc7"
    end
  end

  def install
    bin.install "gorillang"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
